title: Obi Ordu
description: Engineer | Kubernetes & DevOps Expert
url: "https://obiordu.github.io"
author: Obi Ordu
twitter:
  username: username
  card: summary
social:
  name: Obi Ordu
  links:
    - https://www.linkedin.com/in/oscarordu
    - https://github.com/obiordu

show_downloads: false
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Cache settings
defaults:
  - scope:
      path: ""
    values:
      cache_control: no-cache

# Build settings
exclude: [README.md, Gemfile, Gemfile.lock]
keep_files: [.git, CNAME]
incremental: false

# Dark theme customization
github:
  is_project_page: false

# Custom CSS overrides
sass:
  style: compressed
